version: '2'
volumes:
 data-grafana:
  driver: local
services:
 grafana:
  network_mode: host
  image: grafana/grafana:latest
  ports:
      - 3000:3000/tcp
  environment:
   GF_RENDERING_SERVER_URL: http://localhost:8081/render
   GF_RENDERING_CALLBACK_URL: http://localhost:3000/
   GF_LOG_FILTERS: rendering:debug
   GF_AUTH_ANONYMOUS_ENABLED: 'true'
   GF_PANELS_DISABLE_SANITIZE_HTML: 'true'
  volumes:
  - data-grafana:/var/lib/grafana
  - /home/habitox/grafana/grafana.ini:/etc/grafana/grafana.ini
 renderer:
  network_mode: host
  image: grafana/grafana-image-renderer:latest
  ports:
      - 8081:8081/tcp
